import { copyFileSync } from "node:fs";

/**
 * Generate a new UUID for synced thread.
 * Uses crypto.randomUUID() to create a proper UUID v4.
 */
export function generateSyncId(
  originalId: string,
  targetProvider: string
): string {
  // Generate a new UUID v4
  return crypto.randomUUID();
}

/**
 * Check if an ID looks like it was generated by this tool.
 * Since we now use random UUIDs, we can't detect synced IDs by format alone.
 */
export function isSyncedId(id: string, targetProvider: string): boolean {
  // Can't determine from ID alone anymore
  return false;
}

/**
 * Create a backup copy of a file (append .bak timestamp).
 */
export function createBackup(filePath: string): string {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const backupPath = `${filePath}.bak-${ts}`;
  copyFileSync(filePath, backupPath);
  return backupPath;
}

// --- Logger ---

let verboseEnabled = false;

export function setVerbose(v: boolean) {
  verboseEnabled = v;
}

export function log(msg: string) {
  console.log(msg);
}

export function verbose(msg: string) {
  if (verboseEnabled) console.log(`  [verbose] ${msg}`);
}

export function warn(msg: string) {
  console.log(`  [warn] ${msg}`);
}

export function error(msg: string) {
  console.error(`  [error] ${msg}`);
}
